# Generated by Django 5.0.6 on 2024-06-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_image_user_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='previous_diagnosis_class',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_diagnosis_value',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
